// Generated by scripts/build-settings-index.mjs — do not edit by hand.
import type { SettingsSectionId } from "@/lib/settings";

export interface SettingsIndexEntry { section: SettingsSectionId; title: string; description: string | null; group: string | null }

export const SETTINGS_INDEX: SettingsIndexEntry[] = [
 {
  "section": "appearance",
  "title": "Use system UI font",
  "description": "Keeps your chosen font ready when the system override is off.",
  "group": "Interface typography"
 },
 {
  "section": "appearance",
  "title": "Font smoothing",
  "description": null,
  "group": "Interface typography"
 },
 {
  "section": "appearance",
  "title": "Interface animations",
  "description": null,
  "group": "Effects and motion"
 },
 {
  "section": "appearance",
  "title": "Cursor-reactive button effects",
  "description": null,
  "group": "Effects and motion"
 },
 {
  "section": "appearance",
  "title": "Reduce motion",
  "description": "Also respects prefers-reduced-motion from the OS.",
  "group": "Effects and motion"
 },
 {
  "section": "appearance",
  "title": "Background effect",
  "description": null,
  "group": "Chat background"
 },
 {
  "section": "appearance",
  "title": "Show on",
  "description": "Empty sessions only, or every conversation.",
  "group": "Chat background"
 },
 {
  "section": "appearance",
  "title": "Empty chat visibility",
  "description": "Background strength before a chat has messages.",
  "group": "Chat background"
 },
 {
  "section": "appearance",
  "title": "Session visibility",
  "description": "Background strength once the conversation has messages.",
  "group": "Chat background"
 },
 {
  "section": "appearance",
  "title": "Translucency",
  "description": null,
  "group": "Materials"
 },
 {
  "section": "appearance",
  "title": "Apply translucency to",
  "description": null,
  "group": "Materials"
 },
 {
  "section": "appearance",
  "title": "UI font",
  "description": null,
  "group": "Interface typography"
 },
 {
  "section": "appearance",
  "title": "UI font size",
  "description": null,
  "group": "Interface typography"
 },
 {
  "section": "appearance",
  "title": "UI density",
  "description": "Adjusts spacing independently of text size.",
  "group": "Interface typography"
 },
 {
  "section": "appearance",
  "title": "Code font",
  "description": "Applies to transcript code, diffs and the editor.",
  "group": "Code typography"
 },
 {
  "section": "appearance",
  "title": "Code font size",
  "description": null,
  "group": "Code typography"
 },
 {
  "section": "appearance",
  "title": "Terminal font",
  "description": null,
  "group": "Terminal typography"
 },
 {
  "section": "appearance",
  "title": "Terminal font size",
  "description": null,
  "group": "Terminal typography"
 },
 {
  "section": "appearance",
  "title": "Composer line speed",
  "description": "The silver line pauses while the text field is focused.",
  "group": "Effects and motion"
 },
 {
  "section": "appearance",
  "title": "Dock icon",
  "description": null,
  "group": "Application"
 },
 {
  "section": "chat",
  "title": "chatBehavior.fold",
  "description": "chatBehavior.foldHelp",
  "group": "chatBehavior.conversation"
 },
 {
  "section": "chat",
  "title": "chatBehavior.workingPanel",
  "description": "chatBehavior.workingPanelHelp",
  "group": "chatBehavior.conversation"
 },
 {
  "section": "chat",
  "title": "chatBehavior.wrap",
  "description": "chatBehavior.wrapHelp",
  "group": "chatBehavior.review"
 },
 {
  "section": "chat",
  "title": "chatBehavior.confirmArchive",
  "description": "chatBehavior.confirmArchiveHelp",
  "group": "chatBehavior.safety"
 },
 {
  "section": "chat",
  "title": "chatBehavior.confirmTerminal",
  "description": "chatBehavior.confirmTerminalHelp",
  "group": "chatBehavior.safety"
 },
 {
  "section": "chat",
  "title": "chatBehavior.confirmDelete",
  "description": "chatBehavior.confirmDeleteHelp",
  "group": "chatBehavior.safety"
 },
 {
  "section": "computer",
  "title": "windowSnap.enable",
  "description": "windowSnap.enableHelp",
  "group": "windowSnap.title"
 },
 {
  "section": "computer",
  "title": "windowSnap.shortcut",
  "description": "windowSnap.shortcutHelp",
  "group": "windowSnap.title"
 },
 {
  "section": "computer",
  "title": "computer.enable",
  "description": "computer.enableHelp",
  "group": "computer.title"
 },
 {
  "section": "connections",
  "title": "connections.enable",
  "description": "connections.enableHelp",
  "group": "connections.access"
 },
 {
  "section": "connections",
  "title": "connections.keepAwake",
  "description": "connections.keepAwakeHelp",
  "group": "connections.access"
 },
 {
  "section": "connections",
  "title": "connections.address",
  "description": "connections.addressHelp",
  "group": "connections.access"
 },
 {
  "section": "connections",
  "title": "connections.noTailscale",
  "description": "connections.noTailscaleHelp",
  "group": "connections.access"
 },
 {
  "section": "connections",
  "title": "connections.https",
  "description": null,
  "group": "connections.access"
 },
 {
  "section": "connections",
  "title": "connections.httpsSetup",
  "description": "connections.httpsSetupHelp",
  "group": "connections.access"
 },
 {
  "section": "general",
  "title": "Default provider",
  "description": "Choose the provider for new sessions. Current sessions keep their provider.",
  "group": "Core defaults"
 },
 {
  "section": "general",
  "title": "New threads",
  "description": "Choose the default workspace for new sessions.",
  "group": "Core defaults"
 },
 {
  "section": "general",
  "title": "Language",
  "description": null,
  "group": "Core defaults"
 },
 {
  "section": "general",
  "title": "Project order",
  "description": "Pinned projects stay first. Dragging a folder switches to manual order.",
  "group": "Sidebar organization"
 },
 {
  "section": "general",
  "title": "Thread order",
  "description": "Orders sessions inside each project. Pinned sessions keep their own area.",
  "group": "Sidebar organization"
 },
 {
  "section": "general",
  "title": "Reopen last project",
  "description": "Automatically reopen the last active project when Sirus Code starts.",
  "group": "Startup"
 },
 {
  "section": "general",
  "title": "Automatic project icons",
  "description": "Projects without a chosen icon show their own favicon or logo, found in the project folder.",
  "group": "Startup"
 },
 {
  "section": "general",
  "title": "Reopen newest session",
  "description": "Reopen the newest-created session in the last project. Other sessions remain in the sidebar; agents do not start automatically.",
  "group": "Startup"
 },
 {
  "section": "general",
  "title": "Show confirmation before closing running sessions",
  "description": "Ask before closing or quitting while agents are running.",
  "group": "Application"
 },
 {
  "section": "general",
  "title": "Astros in the menu bar",
  "description": "Show the Astros icon in the macOS menu bar, to open an Astro's floating chat.",
  "group": "Application"
 },
 {
  "section": "general",
  "title": "Open by default",
  "description": "Open the chat Environment panel automatically on normal threads. When off, the panel stays closed until you open it. Your last open/close also updates this preference.",
  "group": "Environment panel"
 },
 {
  "section": "general",
  "title": "Repository",
  "description": "Show the repository link in the Environment panel.",
  "group": "Environment panel"
 },
 {
  "section": "general",
  "title": "Editor",
  "description": "Show the editor actions in the Environment panel.",
  "group": "Environment panel"
 },
 {
  "section": "general",
  "title": "Check for updates automatically",
  "description": null,
  "group": "Application"
 },
 {
  "section": "notifications",
  "title": "Activity toasts",
  "description": null,
  "group": "Activity alerts"
 },
 {
  "section": "notifications",
  "title": "System notifications",
  "description": null,
  "group": "Activity alerts"
 },
 {
  "section": "notifications",
  "title": "Notification sounds",
  "description": null,
  "group": "Activity alerts"
 },
 {
  "section": "notifications",
  "title": "Notify while app is in focus",
  "description": null,
  "group": "Activity alerts"
 },
 {
  "section": "mcp",
  "title": "mcp.agents.enable",
  "description": "mcp.agents.enableHelp",
  "group": "mcp.agents.title"
 },
 {
  "section": "providers",
  "title": "Check for CLI updates",
  "description": "Check Codex, Claude and other provider CLIs for newer versions in the background.",
  "group": "Updates"
 },
 {
  "section": "git",
  "title": "Git detected",
  "description": null,
  "group": "Installation"
 },
 {
  "section": "git",
  "title": "Version",
  "description": null,
  "group": "Installation"
 },
 {
  "section": "git",
  "title": "Executable",
  "description": null,
  "group": "Installation"
 },
 {
  "section": "git",
  "title": "Automatically fetch when opening project",
  "description": "Automatic fetch is unavailable while project Git configuration can execute helpers or disclose credentials. Fetch manually in your terminal.",
  "group": "Behavior"
 },
 {
  "section": "git",
  "title": "ciFix.setting",
  "description": "ciFix.settingHelp",
  "group": "Behavior"
 },
 {
  "section": "git",
  "title": "prWatch.setting",
  "description": "prWatch.settingHelp",
  "group": "Behavior"
 },
 {
  "section": "git",
  "title": "Show untracked files",
  "description": null,
  "group": "Behavior"
 },
 {
  "section": "git",
  "title": "Confirm destructive Git actions",
  "description": "Cannot be turned off. Sirus Code never runs reset --hard, clean -fd, or worktree remove --force automatically.",
  "group": "Behavior"
 },
 {
  "section": "worktrees",
  "title": "Default session workspace",
  "description": null,
  "group": "Defaults"
 },
 {
  "section": "worktrees",
  "title": "Worktree location",
  "description": null,
  "group": "Defaults"
 },
 {
  "section": "worktrees",
  "title": "Custom directory",
  "description": null,
  "group": "Defaults"
 },
 {
  "section": "worktrees",
  "title": "Automatic directory",
  "description": null,
  "group": "Defaults"
 },
 {
  "section": "worktrees",
  "title": "Branch naming pattern",
  "description": "Tokens: {session-name} {id}",
  "group": "Defaults"
 },
 {
  "section": "worktrees",
  "title": "Clean up completed worktrees",
  "description": "Removes isolated worktrees for completed, failed, or stopped sessions. Dirty trees are refused without --force.",
  "group": "Cleanup"
 },
 {
  "section": "worktrees",
  "title": "worktreeCleanup.leftovers",
  "description": "worktreeCleanup.leftoversHelp",
  "group": "Cleanup"
 },
 {
  "section": "worktrees",
  "title": "worktreeCleanup.release",
  "description": "worktreeCleanup.releaseHelp",
  "group": "Cleanup"
 },
 {
  "section": "terminal",
  "title": "Default shell",
  "description": null,
  "group": "Shell"
 },
 {
  "section": "terminal",
  "title": "Use system default shell",
  "description": "The PTY always launches $SHELL. This cannot be changed.",
  "group": "Shell"
 },
 {
  "section": "terminal",
  "title": "Working directory behavior",
  "description": null,
  "group": "Shell"
 },
 {
  "section": "terminal",
  "title": "Terminal font",
  "description": null,
  "group": "Display"
 },
 {
  "section": "terminal",
  "title": "Terminal font size",
  "description": null,
  "group": "Display"
 },
 {
  "section": "terminal",
  "title": "Cursor style",
  "description": null,
  "group": "Display"
 },
 {
  "section": "terminal",
  "title": "Scrollback limit",
  "description": null,
  "group": "Display"
 },
 {
  "section": "keybindings",
  "title": "Developer logs",
  "description": "Stores bounded lifecycle counts locally. Prompts, output, paths and credentials are excluded.",
  "group": "Diagnostics"
 },
 {
  "section": "keybindings",
  "title": "Open Sirus Code data directory",
  "description": null,
  "group": "Diagnostics"
 },
 {
  "section": "keybindings",
  "title": "Open logs folder",
  "description": null,
  "group": "Diagnostics"
 },
 {
  "section": "keybindings",
  "title": "Reset window layout",
  "description": "Clears sidebar collapse and panel widths in this session.",
  "group": "Diagnostics"
 },
 {
  "section": "keybindings",
  "title": "UI Arc components",
  "description": "Explore all 100 free components with local examples.",
  "group": "Diagnostics"
 },
 {
  "section": "keybindings",
  "title": "Experimental features",
  "description": null,
  "group": "Diagnostics"
 }
];
