export const queuePortuguese = {
  "queue.title": "Fila de pedidos", "queue.count": "{count} pedidos na fila", "queue.paused": "Pausada", "queue.waiting": "Em espera", "queue.add": "Adicionar à fila", "queue.pause": "Pausar fila", "queue.resume": "Continuar fila",
  "queue.edit": "Editar", "queue.cancel": "Cancelar", "queue.save": "Salvar", "queue.discardEdit": "Fechar edição", "queue.editItem": "Editar pedido {position}", "queue.cancelItem": "Cancelar pedido {position}", "queue.attachmentsOnly": "Analisar anexos",
  "queue.retryOnly": "Este pedido já tentou iniciar. Para mudar o texto, cancele e adicione outro pedido.",
  "queue.manual": "Os pedidos aguardam você continuar a fila.", "queue.failed": "A fila pausou após uma falha ou interrupção. Confira a conversa antes de continuar.", "queue.contextChanged": "O modelo, a conta ou o workspace mudou. Cancele os pedidos e envie-os novamente com a nova escolha.", "queue.invalid": "Escreva um pedido dentro do limite de 64 KiB, incluindo os anexos.", "queue.limit": "A fila aceita até 8 pedidos de 64 KiB cada. Confira também se a troca de modelo terminou.", "queue.sessionOnly": "Os pedidos começam em ordem após uma resposta concluída. A fila fica apenas nesta abertura do app.",
};
export const queueEnglish: Record<keyof typeof queuePortuguese, string> = {
  "queue.title": "Request queue", "queue.count": "{count} queued requests", "queue.paused": "Paused", "queue.waiting": "Waiting", "queue.add": "Add to queue", "queue.pause": "Pause queue", "queue.resume": "Continue queue",
  "queue.edit": "Edit", "queue.cancel": "Cancel", "queue.save": "Save", "queue.discardEdit": "Close editor", "queue.editItem": "Edit request {position}", "queue.cancelItem": "Cancel request {position}", "queue.attachmentsOnly": "Analyze attachments",
  "queue.retryOnly": "This request already attempted to start. To change its text, cancel it and add another request.",
  "queue.manual": "Requests wait until you continue the queue.", "queue.failed": "The queue paused after a failure or interruption. Check the conversation before continuing.", "queue.contextChanged": "The model, account or workspace changed. Cancel the requests and submit them again with the new selection.", "queue.invalid": "Enter a request within the 64 KiB limit, including attachments.", "queue.limit": "The queue holds up to 8 requests of 64 KiB each. Also check that any model change has finished.", "queue.sessionOnly": "Requests start in order after a completed response. The queue lasts for this app run only.",
};
