import assert from "node:assert/strict";
import { test } from "node:test";
import { useAppStore } from "../src/store/app-store.ts";

test("shared history replays settings sections, then returns to the empty project landing", () => {
  const project = { id: "navigation-project", name: "Fixture", path: "/fixture", addedAt: "time", lastOpenedAt: "time" };
  useAppStore.setState({ projects: [project], sessions: [{ id: "existing-session", title: "Existing", projectId: project.id, agent: "codex", status: "idle", messages: [], lastError: null, createdAt: "time", lastActivityAt: "time", worktree: { path: "/fixture", branch: "main", isolated: false } }], selectedProjectId: project.id, selectedSessionId: null, mainView: "session", settingsOpen: false, settingsSection: "general", navHistory: [], navIndex: -1 });
  const state = () => useAppStore.getState();
  state().setSettingsOpen(true);
  state().setSettingsSection("providers");
  state().setSettingsSection("appearance");
  state().goBack();
  assert.equal(state().settingsOpen, true);
  assert.equal(state().settingsSection, "providers");
  state().goForward();
  assert.equal(state().settingsSection, "appearance");
  state().goBack();
  state().goBack();
  assert.equal(state().settingsSection, "general");
  state().goBack();
  assert.equal(state().settingsOpen, false);
  assert.equal(state().selectedProjectId, project.id);
  assert.equal(state().selectedSessionId, null);
  state().goForward();
  assert.equal(state().settingsOpen, true);
  state().setSettingsSection("terminal");
  assert.equal(state().navIndex, state().navHistory.length - 1);
  for (let i = 0; i < 70; i++) state().setSettingsSection(i % 2 ? "git" : "appearance");
  assert.equal(state().navHistory.length, 50);
});
